### ISSUE TITLE
Older bedrock version support

### ISSUE THREAD

**Issue by LegacyGamerHD** [bundabrg/GeyserReversion#16]
Would be awesome to add

**Comment by bundabrg** [comment]
How old are we talking? I've been adding each release as they come since v408.

**Comment by salwador** [comment]
@bundabrg what about support v407? It can be a great if we can get full support 1.16.XX releases, w/o beta's.

**Comment by bundabrg** [comment]
I think 407 was pretty close to 408 so I can add that in.

**Comment by salwador** [comment]
@bundabrg 😍
