### ISSUE TITLE
[BUG] Books on v1.16.40 is invalid item

### ISSUE THREAD

**Issue by salwador** [bundabrg/GeyserReversion#19]
**Versions**
Core: Paper-1.16.4-298
Geyser: Geyser-v1.16-b45
Reversion: GeyserReversion-1.0.22
Minecraft Win10 (right left): 1.16.100
Minecraft PE (left bottom): 1.16.40

**Issue:**
Books on version 1.16.40 displayed as other item.

**Proofs:**
https://www.youtube.com/watch?v=XoV9yVVBDGk&feature=youtu.be

**Comment by bundabrg** [comment]
Looks like the book is being shown as a book + quill so may need an item remap. I'll check it out.

**Comment by salwador** [comment]
Same bug with 1.16.0/10.
