### ISSUE TITLE
[BUG] Put lapis in enchant slot is not working on 1.16.40

### ISSUE THREAD

**Issue by salwador** [bundabrg/GeyserReversion#21]
Versions
Core: Paper-1.16.4-298
Geyser: Geyser-v1.16-b45
Reversion: GeyserReversion-1.0.22
Minecraft Win10 (right left): 1.16.100
Minecraft PE (left bottom): 1.16.40

Issue:
On version 1.16.40 i can't put lapis into enchant slot.

Proofs:
1. https://www.youtube.com/watch?v=4LVveULWmuU&feature=youtu.be
2. (Test with Win10 and 1.16.40) https://www.youtube.com/watch?v=jNv7EXyRquI&feature=youtu.be

**Comment by salwador** [comment]
Same bug with 1.16.0/10.

**Comment by bundabrg** [comment]
Should be fixed in GeyserReversion v1.0.24 once its built. Thanks for the great bug reports.
