### ISSUE TITLE
The number of players is displayed incorrectly

### ISSUE THREAD

**Issue by zimzaza4** [bundabrg/GeyserReversion#23]
![-218aa4a366123054](https://user-images.githubusercontent.com/53421735/101270260-613c9a00-37b2-11eb-9cde-7b352bda606d.jpg)
-1/20
Geyser : 1.16.100
Use Floodgate
Minecraft: 1.16.101

**Comment by bundabrg** [comment]
Without GR running does geyser itself display it correctly?

**Comment by zimzaza4** [comment]
> Without GR running does geyser itself display it correctly?

Yes

**Comment by zimzaza4** [comment]
This problem occurred after I installed it

**Comment by zimzaza4** [comment]
I also turned on this
![Uploading IMG20201206113703.jpg…]()

**Comment by salwador** [comment]
**BedrockEditionServerEventHandler.java**

Missing method? Code not have player count setter.
translatedPong.setPlayerCount(originalPong.getPlayerCount());
