### ISSUE TITLE
Support v423

### ISSUE THREAD

**Issue by zimzaza4** [bundabrg/GeyserReversion#27]
support beta1.16.210?

**Comment by bundabrg** [comment]
I already updated the Reversion library to do this. I just need to bump the version here for the support or I may consider making a beta branch maybe here.

**Comment by bundabrg** [comment]
v423 now supported in v1.0.23. However there seem to be some palette issues with water and skulls that will need investigating so expect some weird looking worlds...

**Comment by zimzaza4** [comment]
![-7f9f5bbfc7d522b7](https://user-images.githubusercontent.com/53421735/102007027-71c7b400-3d60-11eb-99a9-6efe857a3f4b.jpg)
Water is wrong

**Comment by zimzaza4** [comment]
Only happens in beta1.16.210

**Comment by bundabrg** [comment]
Yep, that's the palette issue. Seems to also be something up with skulls.

**Comment by zimzaza4** [comment]
> Yep, that's the palette issue. Seems to also be something up with skulls.

There seems to be no problem with the skulls

**Comment by bundabrg** [comment]
That's interesting. I was having issues where Steve skulls were leaking through custom skulls.

**Comment by zimzaza4** [comment]
Ok.. I did not watch the custom skull

**Comment by zimzaza4** [comment]
Support v424?
