### ISSUE TITLE
Nothing happens when running /geyser education new

### ISSUE THREAD

**Issue by nobbele** [bundabrg/GeyserReversion#31]
no output in chat, the console just says username issued command

**Comment by bundabrg** [comment]
Don't put a slash on the front. So it should just be `geyser new`

**Comment by nobbele** [comment]
not having a slash just sends a chat message, I'm running your geyser fork and the extension is loaded

**Comment by nobbele** [comment]
not related to this issue but idk if I should open a new one, when I try to connect on education it can't find the server for some reason, works on bedrock and java

**Comment by bundabrg** [comment]
actually education should be udp as well, and you'll need to run it on a different port than bedrock. I'll close this if its all solved though.
