### ISSUE TITLE
Could not load plugins GeyserReversion

### ISSUE THREAD

**Issue by Hoangviphb999** [bundabrg/GeyserReversion#37]
It cause this error

**Comment by bundabrg** [comment]
Which version of Geyser and GeyserReversion are you running?

**Comment by Hoangviphb999** [comment]
Sorry for interuppted you, i see your description and download GeyserMC with Extension, i think that was just a plugins for Spigot, thanks for help

**Comment by bundabrg** [comment]
No probs
