### ISSUE TITLE
Minecraft education 14.70

### ISSUE THREAD

**Issue by themarwik** [bundabrg/GeyserReversion#53]
microsoft have updated thair minecraft education to 14.70 and it updates automatic and it not working using the last minecraft education versjon with Gayser Reversion

**Comment by bundabrg** [comment]
I'll be looking at this in the next couple of days with priority.

**Comment by topedu-mee** [comment]
> I'll be looking at this in the next couple of days with priority.

any news? thanks

**Comment by bundabrg** [comment]
[This Version](https://github.com/bundabrg/GeyserReversion/releases/tag/v1.0.36) is now available to support Education 1.14.70. Note that you'll still need to run it against Geyser-v1.16-b55 for now but if you have viaversion on your server it shouldn't be a problem (for now).

**Comment by topedu-mee** [comment]
thank you so much!
