### ISSUE TITLE
Add Support for Education edition beta 1.18.10.04

### ISSUE THREAD

**Issue by MIOGMIOG** [bundabrg/GeyserReversion#62]
Hi, can you please add support for Education edition beta 1.18.10.04?

**Comment by bundabrg** [comment]
Thanks for your issue. I am closing down this project but will be creating a new one that will sit in front of a bedrock server (be it Geyser itself or vanilla) and provide both the version translations as well as provide a plugin interface. I'm hoping this will be easier to maintain. Keep an eye on this projects main README file for updates which will eventually have a link to the new project.

**Comment by bundabrg** [comment]
btw, where does one get the beta?

**Comment by MythicalFlame** [comment]
> btw, where does one get the beta?

https://educommunity.minecraft.net/hc/en-us/articles/4407483028116-Download-Minecraft-Education-Edition-Beta
