### ISSUE TITLE
Education version without TenantID Check?

### ISSUE THREAD

**Issue by ghost** [bundabrg/GeyserReversion#67]
Hi, recently a modification was found to play online on education edition without having a tenant, and, i tried this project to see if it works, but it doesn't, there appears to be an issue with tenantid check, that will not work. There is a version of geyser reversion that works without TenantID? and btw i can't compile this

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/94207445/225469359-21b8d355-933d-48ea-a6d9-c3207f6ebd40.png)

**Comment by bundabrg** [comment]
Sorry I havn't been updating this is a long time as I moved towards trying to create a proxy that can sit in front of Geyser. Do you know more about the tenantid checking? Also depending on how it avoids the check it may only be a temporary thing till they patch it

**Comment by ghost** [comment]
well, the TenantID was removed from exe, so education doesn't check if you been logged in on a school account, with the own tenant geyser actually does check that and i think it gliches out without knowing what to do. The solution that i'm thinking its removing that check, and btw, i send you the modded exe so if you want, you could try it
[1.14.70 V2.zip](https://github.com/bundabrg/GeyserReversion/files/10989305/1.14.70.V2.zip)
https://archive.org/download/minecraft-education-edition-win32/MinecraftEducationEdition_x86_1.14.70.0.exe

**Comment by ghost** [comment]
Servers were cracked now :) only working on versions before 1.12!
