### ISSUE TITLE
Not loading from extensions folder

### ISSUE THREAD

**Issue by dannytech** [bundabrg/GeyserReversion#7]
First of all, I really appreciate the amount of effort you've put into this, and it's pretty amazing what you've accomplished. I've been following your Education Edition issue on the Geyser repo for a while as it's something we've been looking for.

I'm currently running build v1.16-b31 of Geyser from your repository, and GeyserReversion v1.0.11. I originally had GeyserReversion as a plugin but noticed you turned it into an extension, so I tried moving it to the `extensions/` folder, however it does not load when the JAR is in the `extensions/` folder, while it does when it's in the `plugins/` folder. I also noticed the configuration file is still created and read from the `extensions/` folder even though the JAR is in the `plugins/` folder.

**Comment by bundabrg** [comment]
Problem is solved in [the extensions](https://github.com/bundabrg/Geyser/tree/feature/plugins) tree of Geyser. I'll push a new bleeding build now as well.
