### ISSUE TITLE
Floodgate Issue

### ISSUE THREAD

**Issue by 200Tigersbloxed** [bundabrg/GeyserReversion#9]
Hey, finally got this working after switching JDK version, so I tried it out on a test server.

When I had my server in Offline Mode (and Geyser too), I was able to join the server just fine.
In Online mode, I was also able to join the server, just had to login.

But when I tried to join using Floodgate, to use online mode, and skip the login, Geyser and the Server outputs Warnings.

Geyser Warning:
`[Geyser-Spigot] Downstream packet error! Invalid packet id: 25`

Server INFO:
`x:x lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/0 (PacketPlayInTeleportAccept) was larger than I expected, found 5 bytes extra whilst reading packet 0`

Then after that, Minecraft:EE says Connection Lost

Server Spec:
PaperMC 175
Plugins:
+ Viaversion
+ ViaBackwards
+ ViaRewind
+ Geyser (with plugins ofc)
+ Floodgate

If you need any more details, please respond, and I'll try to get them to you.

**Comment by bundabrg** [comment]
Thanks. I suspect the floodgate section of code is being skipped as GeyserReversion handles a lot of the login first and it might never reach floodgate in geyser itself.

I'll have a look. Perhaps either a change in Geyser to split calling floodgate outside of the login packet function (so we can just call it ourselves) or I re-implement the floodgate part here as well.

**Comment by edwardhuahan** [comment]
I'm also experiencing the same issue with the same error message
